### ISSUE TITLE
WeatherLocationCode | Update README.md

### ISSUE THREAD

**Issue by ivadham** [kloverde/Win7WeatherGadgetRepairTool#4]
**Select current location manually**

“Search for location” may not work. 
Use [Weather Location Codes/IDs](https://weather.codes/) to find your `WeatherLocationCode`.
Open `%localappdata%\Microsoft\Winsows Sidebar\Settings.ini` and paste it.

**Comment by kloverde** [comment]
Thanks for this tip.  I've added it to the wiki.
